// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mikhtav.Infrastructure.Data;

#nullable disable

namespace Mikhtav.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mikhtav.Core.Models.BureauTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MeaningEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeaningRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeaningUk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("TermHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transliteration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsageNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Glossary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MeaningEn = "Identity card. The mandatory national ID for residents — its 9-digit number identifies you to every government office.",
                            MeaningRu = "Удостоверение личности. Обязательный национальный документ для жителей — его 9-значный номер используется во всех государственных учреждениях.",
                            OrderIndex = 1,
                            TermHe = "תעודת זהות",
                            Transliteration = "Te'udat Zehut"
                        },
                        new
                        {
                            Id = 2,
                            MeaningEn = "Case/file number. Always quote this number when calling or writing about a specific letter or matter.",
                            MeaningRu = "Номер дела/папки. Всегда указывайте этот номер при обращении по конкретному вопросу или письму.",
                            OrderIndex = 2,
                            TermHe = "מספר תיק",
                            Transliteration = "Mispar Tik"
                        },
                        new
                        {
                            Id = 3,
                            MeaningEn = "National Insurance Institute. Israel's social-security agency, handles pensions, unemployment, maternity, disability and more.",
                            MeaningRu = "Битуах Леуми (Институт национального страхования) — израильское ведомство социального обеспечения: пенсии, пособия по безработице, материнству, инвалидности и т.д.",
                            OrderIndex = 3,
                            TermHe = "ביטוח לאומי",
                            Transliteration = "Bituach Leumi"
                        },
                        new
                        {
                            Id = 4,
                            MeaningEn = "Income Tax (Authority). The Israel Tax Authority — assesses and collects personal and corporate income tax.",
                            MeaningRu = "Подоходный налог (управление). Налоговое управление Израиля — рассчитывает и собирает подоходный налог с физических и юридических лиц.",
                            OrderIndex = 4,
                            TermHe = "מס הכנסה",
                            Transliteration = "Mas Hachnasa"
                        },
                        new
                        {
                            Id = 5,
                            MeaningEn = "Payment demand. An official request to pay an outstanding amount by a stated date.",
                            MeaningRu = "Требование об оплате. Официальное требование уплатить указанную сумму до определённой даты.",
                            OrderIndex = 5,
                            TermHe = "דרישת תשלום",
                            Transliteration = "Drishat Tashlum"
                        },
                        new
                        {
                            Id = 6,
                            MeaningEn = "Final deadline. The last date by which action must be taken without penalty.",
                            MeaningRu = "Крайний срок. Последняя дата, до которой можно действовать без штрафа.",
                            OrderIndex = 6,
                            TermHe = "מועד אחרון",
                            Transliteration = "Moed Acharon"
                        },
                        new
                        {
                            Id = 7,
                            MeaningEn = "Appeal / objection. A formal challenge to a decision; most have a strict filing window (often 30 days).",
                            MeaningRu = "Возражение / апелляция. Официальное оспаривание решения; обычно действует строгий срок подачи (часто 30 дней).",
                            OrderIndex = 7,
                            TermHe = "ערעור",
                            Transliteration = "Erur",
                            UsageNote = "Always submit in writing and keep proof of receipt."
                        },
                        new
                        {
                            Id = 8,
                            MeaningEn = "Confirmation or approval. A document or letter that confirms a status, eligibility, or completed action.",
                            MeaningRu = "Подтверждение или утверждение. Документ или письмо, подтверждающее статус, право или совершённое действие.",
                            OrderIndex = 8,
                            TermHe = "אישור",
                            Transliteration = "Ishur"
                        },
                        new
                        {
                            Id = 9,
                            MeaningEn = "Explanatory note. The supplementary page attached to a letter that explains the figures or decisions on the main page.",
                            MeaningRu = "Пояснительная записка. Дополнительная страница к письму, поясняющая цифры или решения, указанные на основной странице.",
                            OrderIndex = 9,
                            TermHe = "הסבר נלווה",
                            Transliteration = "Hesber Nilve"
                        },
                        new
                        {
                            Id = 10,
                            MeaningEn = "Clause or section. Refers to a numbered paragraph of a law or document.",
                            MeaningRu = "Пункт или раздел. Обозначает пронумерованный пункт закона или документа.",
                            OrderIndex = 10,
                            TermHe = "סעיף",
                            Transliteration = "Sa'if"
                        },
                        new
                        {
                            Id = 11,
                            MeaningEn = "Validity. The period during which a document, permit, or approval is in force.",
                            MeaningRu = "Срок действия. Период, в течение которого документ, разрешение или одобрение действительны.",
                            OrderIndex = 11,
                            TermHe = "תוקף",
                            Transliteration = "Tokef"
                        },
                        new
                        {
                            Id = 12,
                            MeaningEn = "Exemption. Relief from an obligation — most commonly tax, but also fees or service requirements.",
                            MeaningRu = "Льгота / освобождение. Освобождение от обязательства — чаще всего от налога, но также от сборов или иных требований.",
                            OrderIndex = 12,
                            TermHe = "פטור",
                            Transliteration = "Ptur"
                        },
                        new
                        {
                            Id = 13,
                            MeaningEn = "Enforcement / Bailiff's Office. The civil debt-collection authority. If your case reaches here, your bank account can be frozen and assets seized.",
                            MeaningRu = "Исполнительная служба (Хотzаа ла-Поэль). Гражданское ведомство по взысканию долгов. Если дело передано сюда, могут заморозить счёт и арестовать имущество.",
                            OrderIndex = 13,
                            TermHe = "הוצאה לפועל",
                            Transliteration = "Hotza'a la-Po'al",
                            UsageNote = "If you receive a letter from here, respond immediately — do not ignore it."
                        },
                        new
                        {
                            Id = 14,
                            MeaningEn = "Interest. Added to overdue amounts; can also refer to interest you owe or are owed under a law.",
                            MeaningRu = "Проценты. Начисляются на просроченные суммы; могут также относиться к процентам, которые вы должны или которые причитаются вам по закону.",
                            OrderIndex = 14,
                            TermHe = "ריבית",
                            Transliteration = "Ribit"
                        },
                        new
                        {
                            Id = 15,
                            MeaningEn = "Regulation. A binding rule issued under the authority of a law. Often cited by number (e.g. \"Takana 2(a)\").",
                            MeaningRu = "Положение / постановление. Обязательное правило, изданное на основании закона. Часто указывается номером (например, «Takana 2(a)»).",
                            OrderIndex = 15,
                            TermHe = "תקנה",
                            Transliteration = "Takana"
                        });
                });

            modelBuilder.Entity("Mikhtav.Core.Models.LetterCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameUk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Issuer = "National Insurance Institute",
                            NameEn = "National Insurance",
                            NameHe = "ביטוח לאומי",
                            NameRu = "Национальное страхование",
                            OrderIndex = 1,
                            Slug = "bituach-leumi"
                        },
                        new
                        {
                            Id = 2,
                            Issuer = "Israel Tax Authority",
                            NameEn = "Income Tax",
                            NameHe = "מס הכנסה",
                            NameRu = "Налоговое управление",
                            OrderIndex = 2,
                            Slug = "mas-hachnasa"
                        });
                });

            modelBuilder.Entity("Mikhtav.Core.Models.LetterSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionRequiredEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionRequiredRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionRequiredUk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deadline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExplainerEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExplainerRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExplainerUk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LetterTypeId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LetterTypeId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionRequiredEn = "If anything is wrong, contact your local Bituach Leumi branch.",
                            ActionRequiredRu = "Если что-то указано неверно, обратитесь в местное отделение Битуах Леуми.",
                            ExplainerEn = "Personal details — check your name, ID number (teudat zehut), and address are spelled correctly. Errors here are the most common cause of payments going to the wrong person.",
                            ExplainerRu = "Личные данные — проверьте, что ваше имя, номер удостоверения (теудат зеут) и адрес указаны верно. Ошибки в этой части — самая частая причина того, что выплаты приходят не тому человеку.",
                            LabelHe = "פרטים אישיים",
                            LetterTypeId = 1,
                            OrderIndex = 1,
                            Severity = 1
                        },
                        new
                        {
                            Id = 2,
                            ExplainerEn = "Coverage start date — the date on which your national insurance enrolment becomes active. Some benefits (maternity, work injury) only apply after a qualifying period that starts from this date.",
                            ExplainerRu = "Дата начала страхования — день, с которого ваше национальное страхование вступает в силу. Некоторые виды пособий (по беременности, в связи с травмой на работе) применяются только после определённого периода с этой даты.",
                            LabelHe = "תאריך תחילת הביטוח",
                            LetterTypeId = 1,
                            OrderIndex = 2,
                            Severity = 0
                        },
                        new
                        {
                            Id = 3,
                            ExplainerEn = "Insurance categories — the benefit programs you're enrolled in (e.g. old age, disability, maternity, unemployment, work injury). Each category has its own eligibility rules.",
                            ExplainerRu = "Категории страхования — программы пособий, к которым вы относитесь (например, по старости, инвалидности, материнству, безработице, травмам на работе). У каждой категории — свои условия.",
                            LabelHe = "קטגוריות הביטוח",
                            LetterTypeId = 1,
                            OrderIndex = 3,
                            Severity = 0
                        },
                        new
                        {
                            Id = 4,
                            ActionRequiredEn = "If you're self-employed, set up a standing order so payments aren't missed — late contributions can interrupt benefit eligibility.",
                            ActionRequiredRu = "Если вы самозанятый, оформите автоматический платёж, чтобы не пропускать взносы — просрочки могут привести к потере права на пособия.",
                            Deadline = "Monthly, on the date shown",
                            ExplainerEn = "Monthly contribution — the amount you pay (or that's deducted from your salary) each month. Self-employed or unemployed people pay directly; salaried employees usually have it withheld by the employer.",
                            ExplainerRu = "Месячный взнос — сумма, которую вы платите (или которая удерживается из зарплаты) каждый месяц. Самозанятые и безработные платят напрямую; у наёмных работников взнос обычно удерживает работодатель.",
                            LabelHe = "סכום החיוב החודשי",
                            LetterTypeId = 1,
                            OrderIndex = 4,
                            Severity = 1
                        },
                        new
                        {
                            Id = 5,
                            ExplainerEn = "Contact details — phone number and address of your assigned branch. Use the case number (mispar tik) shown on the letter whenever you contact them.",
                            ExplainerRu = "Контактные данные — телефон и адрес вашего отделения. При обращении всегда указывайте номер дела (миспар тик), указанный в письме.",
                            LabelHe = "פרטי יצירת קשר",
                            LetterTypeId = 1,
                            OrderIndex = 5,
                            Severity = 0
                        },
                        new
                        {
                            Id = 6,
                            ExplainerEn = "Tax year — the calendar year this demand relates to. In Israel the tax year matches the calendar year (January through December).",
                            ExplainerRu = "Налоговый год — календарный год, к которому относится требование. В Израиле налоговый год совпадает с календарным (январь — декабрь).",
                            LabelHe = "שנת המס",
                            LetterTypeId = 2,
                            OrderIndex = 1,
                            Severity = 0
                        },
                        new
                        {
                            Id = 7,
                            ActionRequiredEn = "Compare this figure against your own records. If it's wrong, you can dispute the demand within 30 days.",
                            ActionRequiredRu = "Сверьте сумму со своими записями. Если она неверна, вы можете подать возражение в течение 30 дней.",
                            ExplainerEn = "Reported income — the income figure on which the tax was calculated. This is based on your or your employer's filings (Form 106 from your employer is the most common source).",
                            ExplainerRu = "Заявленный доход — сумма дохода, по которой рассчитан налог. Берётся из ваших деклараций или деклараций работодателя (чаще всего из формы 106).",
                            LabelHe = "הכנסה מדווחת",
                            LetterTypeId = 2,
                            OrderIndex = 2,
                            Severity = 1
                        },
                        new
                        {
                            Id = 8,
                            ExplainerEn = "Amount owed — the total tax due, often including penalties and interest (ribit) on any underpayment. A negative amount means you're owed a refund.",
                            ExplainerRu = "Сумма задолженности — общий налог к уплате, обычно с пенями и процентами (рибит) за недоплату. Отрицательная сумма означает, что вам должны возврат.",
                            LabelHe = "סכום החוב",
                            LetterTypeId = 2,
                            OrderIndex = 3,
                            Severity = 2
                        },
                        new
                        {
                            Id = 9,
                            ActionRequiredEn = "Pay via Bank HaPoalim / online banking / the Tax Authority website. Keep proof of payment.",
                            ActionRequiredRu = "Оплата возможна через Банк ха-Поалим / онлайн-банк / сайт Налогового управления. Сохраните подтверждение оплаты.",
                            Deadline = "Date shown on the notice (typically 30 days)",
                            ExplainerEn = "Payment deadline — pay by this date to avoid additional interest charges and to keep the case out of enforcement (hotza'a la-po'al).",
                            ExplainerRu = "Крайний срок оплаты — заплатите до этой даты, чтобы избежать новых процентов и не попасть в исполнительное производство (hотzаа ла-поэль).",
                            LabelHe = "מועד תשלום אחרון",
                            LetterTypeId = 2,
                            OrderIndex = 4,
                            Severity = 2
                        },
                        new
                        {
                            Id = 10,
                            ActionRequiredEn = "If the amount is large, consider consulting an accountant (ro'eh cheshbon) before submitting the appeal.",
                            ActionRequiredRu = "Если сумма значительная, имеет смысл проконсультироваться с бухгалтером (роэ хешбон) перед подачей возражения.",
                            Deadline = "30 days from notice receipt",
                            ExplainerEn = "How to appeal — if you disagree with the calculation, file a written objection (erur) within 30 days of receiving the notice. State the tax year, case number, and the specific item you're disputing.",
                            ExplainerRu = "Как подать возражение — если вы не согласны с расчётом, подайте письменное возражение (эрур) в течение 30 дней с момента получения уведомления. Укажите налоговый год, номер дела и оспариваемую позицию.",
                            LabelHe = "אופן הגשת ערעור",
                            LetterTypeId = 2,
                            OrderIndex = 5,
                            Severity = 1
                        });
                });

            modelBuilder.Entity("Mikhtav.Core.Models.LetterType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameUk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SummaryEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryUk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Letters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            NameEn = "National Insurance Enrolment Confirmation",
                            NameHe = "אישור ביטוח לאומי",
                            NameRu = "Подтверждение регистрации в Битуах Леуми",
                            OrderIndex = 1,
                            Slug = "ishur-bituach",
                            SummaryEn = "Confirms that your national insurance file is active and lists the benefit categories you're enrolled in.",
                            SummaryRu = "Подтверждает, что ваше дело в Битуах Леуми активно, и перечисляет категории страхования, к которым вы относитесь."
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            NameEn = "Annual Tax Demand Notice",
                            NameHe = "הודעת דרישה שנתית",
                            NameRu = "Годовое требование об уплате налога",
                            OrderIndex = 1,
                            Slug = "drisha-shnatit",
                            SummaryEn = "An assessment from the Tax Authority of how much you owe (or are owed) for a given tax year, with a payment or appeal deadline.",
                            SummaryRu = "Расчёт Налогового управления о сумме, которую вы должны (или которая причитается вам) за налоговый год, с указанным сроком оплаты или подачи возражения."
                        });
                });

            modelBuilder.Entity("Mikhtav.Core.Models.LetterSection", b =>
                {
                    b.HasOne("Mikhtav.Core.Models.LetterType", "LetterType")
                        .WithMany("Sections")
                        .HasForeignKey("LetterTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LetterType");
                });

            modelBuilder.Entity("Mikhtav.Core.Models.LetterType", b =>
                {
                    b.HasOne("Mikhtav.Core.Models.LetterCategory", "Category")
                        .WithMany("LetterTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Mikhtav.Core.Models.LetterCategory", b =>
                {
                    b.Navigation("LetterTypes");
                });

            modelBuilder.Entity("Mikhtav.Core.Models.LetterType", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
